### ISSUE TITLE
`client disconnect` disconnects all the devices reserved by particular farm account

### ISSUE THREAD

**Issue by dimashabalin** [e13mort/stf-console-client#15]
client disconnects all devices reserved by particular farm account, even those which weren't linked by "this" `client connect`

subj is crucial for CI system because due to particular adb token can be linked with only one farm account so concurrent builds / jobs will affect each other. If one job disconnect all another will lose all the devices during build run

**Comment by e13mort** [comment]
Implemented in 0.3.4 version with -s <serial1, serialN> parameter for the disconnect command.
Please take a look.
