### ISSUE TITLE
Add possibility to connect multiple devices via different names

### ISSUE THREAD

**Issue by dimashabalin** [e13mort/stf-console-client#8]
subj. E.g. stf -c -n "Nexus 5" -n "Nexus 9" -n "Xperia Tablet"
currently it will only connect first one and ignore others

**Comment by e13mort** [comment]
Is the <-n "Nexus 5,Nexus 9,Xperia Tablet"> command might be useful?

**Comment by e13mort** [comment]
fixed in 0.2.1
